### ISSUE TITLE
To those considering using this. Don't. Please read thread. Insecure/hard-coded. A hacked site waiting to happen

### ISSUE THREAD

**Issue by hybridwebdev** [bovas85/nuxt-headless#1]
First and foremost, sorry, but the fact you have things like allow all cors in this package, you're essentially exposing anyone that uses this to massive security vulnerabilities. That in itself is enough reason to say this package should not be used for production.

Second, the fact you're packaging a bunch of potentially premium plugins in this repo, again, makes it not useable. You cannot just include other authors code, as you're breaking all sorts of licensing agreements. 

Third, the code itself that comprises this package is really bad. For example, your store is essentially hardcoded. You are using mutations to alter ordering when you SHOULD be using getters for that sort of thing. 

TLDR: To anyone considering using this repo. Don't. You're asking for a LOT of issues.

To author, I'd suggest making this repo private and re-factoring things considerably before you release this as production ready code. You're doing potential users a disservice by providing it in it's current state.

**Comment by bovas85** [comment]
Hi @hybridwebdev , Thanks for the input.
I'm interested in which security issues you are referring to specifically.

Cors is set to all for a dev environment. Anyone working with CORS should know what they are doing.
Also, CORS is set in the wordpress plugin, but can be easily changed in the config as I mentioned in the blog.

Which premium plugin are you referring to? Advanced custom fields pro is not included in this repo as it's licensed, and people can freely use ACF standard edition, which is distributable :)

The store is just an example, everyone should just make their own store.

I disagree with getters though. You should only be using getters sparingly, as they are quite heavy.
If you use that state in several locations it makes sense to set up some getters in Vuex, but otherwise a computed property is perfectly fine.

This is by no means production ready, it's just a boilerplate to take and use as you wish.

I'm keeping this open for discussion, but when doing Github issues, please be more professional and less aggressive ;)

**Comment by hybridwebdev** [comment]
Okay so, first and foremost, there's absolutely no reason to ever use wildcards for CORS.  Even in development it's unnecessary. Sorry if i came across as "aggressive" but it's just as irresponsible for me to turn a blind eye, as it is for you to release vulnerable software. As a community, it's our job to ensure the software we release is of a certain standard of quality. Saying "Oh, well xx dev should KNOW to configure it prior to launching" is irresponsible. 

As for not using getters because they have a lot of overhead, please elaborate on that. I'm not sure what leads you to believe getters are heavy functions, but that simply isn't true. Given you have this misconception about something so simple as how a getter works, perhaps you need to reconsider if you're ready to release software based on it. 

Again, i apologize if I come across as 'aggressive', but there's got to be some sort of quality control to ensure people aren't wasting their time on poor quality software.

**Comment by bovas85** [comment]
The plugin for cors doesn't use a wildcard at all. When you add the plugin it starts as disabled. The user then can configure it within the WordPress dashboard. I don't believe this is a security issue.

If you have a better idea for this, please suggest. I'm very open to constructive feedback. 

Regarding getters, please see this helpful article:

“Vuex getters are great, but don’t overuse them” by Anya Pavlova https://link.medium.com/whIWWajvDS

I appreciate your clarifications about the tone. But I believe that the title of this 'issue' is quite aggressive. 

I've been using this method for 5 live websites and it's been very solid and secure so far.

**Comment by hybridwebdev** [comment]
> wordpress/wp-content/themes/moustache/index.php line 4, I dont know why homepage redirect too many time and display error

Oh dear god, I didn't even look at that file. I once again echo my sentiments about how god awful this package is. Seriously, please, pull this repo dude. You can't release crap like this out in the public.

**Comment by thoaitrieu** [comment]
yes and some hardcoded in assets/config.js

**Comment by hybridwebdev** [comment]
> yes and some hardcoded in assets/config.js

I reallllly would suggest deleting this package and trying something else man. I'm gunna look into how to possibly report this repo and have it pulled if OP won't do so voluntarily.

**Comment by hybridwebdev** [comment]
Re-opened as this needs to remain visible to those considering using this. However, I don't see anything productive coming from any further discussion regarding issue.

**Comment by bovas85** [comment]
Regarding assets, that's a config where you need to  change the url depending on your wordpress location.

For the theme file, you don't have to use it (and it's not active as default) but that only redirects if it doesn't find a post / page and can be removed. 

Regarding the other comments. I've taken the positive feedback and actioned some points. 

Anything else is pure hate and will be reporter.
