### ISSUE TITLE
Demo site does not work

### ISSUE THREAD

**Issue by lacoste-sochi** [bovas85/nuxt-headless#18]
Hello ! Thank you for sharing your work. Please make a demo site, and there is a lack of documentation to deploy the project.

**Comment by bovas85** [comment]
Hey, thanks for the issue. I tried visiting https://nuxt-headless.netlify.com/ and can see it working. Do you have any more information on the issue?

Deployment should be in the readme. I suggest netlify for static sites or now for node apps

**Comment by rajesh-h** [comment]
@bovas85    I see Demo site is not working. Could you please look into this?
I am attaching the screenshot.

![Screenshot from 2019-10-19 07-53-57](https://user-images.githubusercontent.com/6675921/67138572-e929b280-f245-11e9-94cc-40f59bb0d8a2.png)

**Comment by bovas85** [comment]
Thanks for signalling, I'll take a look now

**Comment by bovas85** [comment]
That is fixed now, thanks

**Comment by rajesh-h** [comment]
I am seeing a picture of Butterfly and when i go down nothing is visible apart from Email. Is this expected?

**Comment by bovas85** [comment]
yes

**Comment by rajesh-h** [comment]
@bovas85 are these above sites SSR sites or offline generated?  I also happen to see the performance here `https://developers.google.com/speed/pagespeed/insights/` it's slightly on the lower side.

Anyway this is not a negative comment, just a observation.

**Comment by bovas85** [comment]
Antilophia is SSR, while others are static.
Unfortunately due to the budget the performance wasn't taken too much into consideration when building them. In terms of client base the performance was deemed acceptable. 

https://nunziellasalluce.com is the only one I spent some time on performance gains and should be higher in score I believe.

Feel free to make a PR on that repo if you have any more performance boosts, it'd be appreciated. It's https://github.com/bovas85/nunziellasalluce.com

**Comment by rajesh-h** [comment]
Yes you are right https://nunziellasalluce.com has good performance boost.

I will see when my site goes on what score i will get :)

**Comment by bovas85** [comment]
Indeed, please let me know if you need any help

**Comment by rajesh-h** [comment]
Thank you very much for the support.

Have you hidden the actual wordpress content from viewing?

I went here https://api.nunziellasalluce.com/ thinking there will be wordpress pages/posts but none is visible. I see rest-api is accessible.

**Comment by bovas85** [comment]
The admin panel is wp-admin but password protected of course.

REST API is at https://api.nunziellasalluce.com/wp-json/wp/v2/ example for pages : https://api.nunziellasalluce.com/wp-json/wp/v2/pages

**Comment by rajesh-h** [comment]
Not Admin site. I ma talking about the Default homepage of your wordpress installation. my expectation was you will have posts or pages on that first page. Definitely it's not for clients.   

I am not sure whether you are getting me or not.

Meanwhile I tried looking for you in discordapp, could not find you.

**Comment by bovas85** [comment]
Wordpress doesn't serve the frontend at all. It's headless as the name implies. My name in Discord is Moustache Design, should be in the blog post too. However I'm on holiday currently so unlikely to read it

**Comment by rajesh-h** [comment]
Enjoy your holiday :)

When you say headless are you saying do you do some kind of changes to the wordpress during the installation?  I was under impression it's a regular implementation of wordpress. just that it's front end is not exposed to clients rather nuxt front end is exposed. looks like I am wrong.

**Comment by rajesh-h** [comment]
Ok looks like you activate kind of blank theme to give a feel of headlless may be

**Comment by bovas85** [comment]
Headless cms means there's no Frontend..
You are looking too much into this. 

API. Is not meant to have a Frontend. The website url is completely different
