### ISSUE TITLE
Handling Yoast SEO redirects

### ISSUE THREAD

**Issue by simplenotezy** [bovas85/nuxt-headless#31]
Hi! Great repo. Did you think about how you could handle Yoast SEO redirects? Or for that matter, Yoast Meta Description/Title/etc?

**Comment by bovas85** [comment]
I couldn't get yoast to work, so I usually create acf for keywords and description

**Comment by simplenotezy** [comment]
Okay. Curious to know; what couldn't you get to work? Anyhow, sounds great to use ACF instead - Yoast takes quite some performance

**Comment by bovas85** [comment]
you can still evaluate with yoast if you can make it work using ACF on that page, but it won't send the keyword/description data to the page so I just oped for an SEO custom field that has keyword/description and title plus SEO images instead
