### ISSUE TITLE
Undefined vm.acf.hero.title etc...

### ISSUE THREAD

**Issue by tiptronic** [bovas85/nuxt-headless#4]
Hi Alessandro,
when installing Wordpress on a server (with valid certificate) the aforementioned certification error goes away.

But when I run the project, I am getting this error:
pages/index.js:360:50 Cannot read property 'title' of undefined (because Vue doesn't find e.g. 'vm.acf.hero.title' -> That's obviously because I don't have any content yet. So it seems I missed something…
Do I need to add some 'acf' defined (and how)? (e.g. vm.acf.hero.title).

Also, the code refers to `config.api.projects`, which is not set in the `config.js` and there's also no post-type (route) to 'project. Do I need to define my own?

Sorry, if I missed something obvious...

andy

**Comment by bovas85** [comment]
Hi Andy, you need to populate your custom fields. 

This is a boilerplate with some examples of how you would be able to implement, but you can remove the pages you don't need and start from scratch if you wish.

You need to have custom fields that match that, or retrieve your own and change accordingly.

Feel free to ask more questions, I'll close this but you can still ad comments.
