### ISSUE TITLE
Wordpress.com

### ISSUE THREAD

**Issue by Berkmann18** [bovas85/nuxt-headless#5]
Would that boilerplate work well with Wordpress.com (the hosted version) or only with Wordpress.org (the self-hosted one)?

**Comment by bovas85** [comment]
I'm not sure if Wordpress.com has an ACF to rest and a rest api exposed @Berkmann18 

This is only supporting Wordpress.org :)

**Comment by Berkmann18** [comment]
@bovas85 Judging by their docs, they seem to have one for wordpress.com but it's not that clear so I asked them.

**Comment by bovas85** [comment]
Thanks, let me know how it goes. Would be interested to extend if possible

**Comment by Berkmann18** [comment]
Will do.

**Comment by Berkmann18** [comment]
The API is accessible via URLs:
- API endpoint: `https://public-api.wordpress.com/rest/v1/sites/:url`
- API endpoint for posts: `https://public-api.wordpress.com/rest/v1/sites/:id/posts/`

Example of gridpressblog.wordpress.com:
- API: https://public-api.wordpress.com/rest/v1/sites/gridpressblog.wordpress.com
- API endpoint for posts: https://public-api.wordpress.com/rest/v1/sites/159743731/posts/

I haven't tried those URLs in Nuxt/Gridsome yet tho.

**Comment by bovas85** [comment]
those that expose custom fields?
My boilerplate doesn't actually depend from any endpoint. This could be adapted to any CMS really, it's just done with WordPress.org as it's free and farily well-known

**Comment by Berkmann18** [comment]
>those that expose custom fields?
You mean the API?

What do you suggest to get it working with wordpres.com?

**Comment by bovas85** [comment]
Simply change the config endpoints and populate the store with the data you receive.
