### ISSUE TITLE
link wordpress backend with nuxt frontend.

### ISSUE THREAD

**Issue by Cally99** [bovas85/nuxt-headless#67]
Hi there,

Thanks for sharing the repo. I've been looking for a a repo with nuxt and wordpress.
I'm struggling to get the wp backend and frontend to talk.

I didn't follow the guide exactly. I'm not that familiar with wordpress so I used a docker image to build and set up wordpress.
I have the theme running and moustache & the 16 plugins activated. I also got the permalinks set to post name.

The one thing I can't figure out is why I can't see the rendered page in wordpress under the frontend url?

so my nuxt app is on **localhost:3000**
& the sample page is under **http://127.0.0.1/sample-page/**

Should the sample page be synced with localhost:3000?

How do I get the wordpress pages to be published in the frontend? Thanks

**Comment by bovas85** [comment]
Hey, thanks for checking this out.

Wordpress does not serve the website. Your site will be hosted under a different port.

Can you reach the wp-json REST API from wordpress? I assume that would be http://127.0.0.1/wp-json/

**Comment by Cally99** [comment]
@bovas85 yes I can reach this url and see the json response. I was wondering if this boilerplate is similar to wuxt or nuxtpress. Both of these setups use docker-compose and I'm having great difficulty using docker to develop with. It's too slow for nuxt to render pages and rebuild containers.

I'd like to build some content in wordpress admin and see the changes published on the frontend. 
Does this repo achieve this?

**Comment by bovas85** [comment]
@Cally99 I honestly didn't bother with Docker. Spinning up a wordpress staging env in the domain was good enough for my use cases but I'm sure you can use Docker for it too if needed.

The only thing this makes easier is to work with the JSON REST API in Wordpress in a headless fashion

**Comment by Cally99** [comment]
@bovas85 docker and has had a negative effect on my workflow over the past two years using it with projects.
With Django and many other backends it works well with docker but with node and nuxt they're in my opinion incompatible. Nuxt Is far too slow working in a docker container. I actually moved over to strapi and next js and I'm very surprised how clean the workflow is. Thanks for letting me know about how this boilerplate works.
